name: DEV Deploy Laravel to Heroku

on:
  push:
    branches:
      - dev  # Cambia esto al nombre de tu rama de desarrollo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Cambia esto a la versión de PHP que usas
          extensions: mbstring, xml, bcmath, curl, zip

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Cambia esto a la versión de Node.js que usas

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Install Node.js dependencies
        run: npm install  # O `yarn install` si usas Yarn

      - name: Compile assets
        run: npm run build  # O el comando que uses para compilar tus activos

      - name: 'Install Heroku CLI'
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: 'Login to Heroku'
        run: |
          heroku auth:token "2e25e507-ccd4-4a85-9b1a-a140b7814cb2"
          heroku git:remote -a karlyoka-web-dev

      - name: 'Deploy to Heroku'
        run: |
          git push heroku main
#      - name: Generate application key
#        run: php artisan key:generate --no-interaction

#      - name: Run database migrations
#        run: php artisan migrate --force

      #- name: Seed database
      #  run: php artisan db:seed --force  # Ejecuta la siembra de datos

#      - name: Deploy to Heroku
#        uses: akhileshns/heroku-deploy@v3.13.15
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: karlyoka-web-dev # Reemplaza con el nombre de tu app en Heroku
#          heroku_email: leomogiano@outlook.com  # Reemplaza con tu email de Heroku

