name: DEV Deploy Laravel to Heroku

on:
  push:
    branches:
      - dev  # Cambia esto al nombre de tu rama de desarrollo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Push to Heroku
#        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/karlyoka-web-dev.git HEAD:main --force

#      - name: Generate application key
#        run: php artisan key:generate --no-interaction

#      - name: Run database migrations
#        run: php artisan migrate --force

      #- name: Seed database
      #  run: php artisan db:seed --force  # Ejecuta la siembra de datos

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: 2e25e507-ccd4-4a85-9b1a-a140b7814cb2 #${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: karlyoka-web-dev # Reemplaza con el nombre de tu app en Heroku
          heroku_email: leomogiano@outlook.com  # Reemplaza con tu email de Heroku

